addons:
  postgresql: 9.6
  code_climate:
    repo_token: 40353e6737489eed237336806e08aff06c6eb3e773659ba31fcd083c6ca9ddc9
after_success:
- bundle exec codeclimate-test-reporter
dist: trusty
language: ruby
rvm:
- 2.4.3
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: aVTUvqhje9Z8MCBlDrgiXVQlMpvbFGcj4D4StXIUaiXlvd53nmNbt16I2sCDP7VK7HutvEembaE9jdMd1rdaBtfej+Bcr1BKl/IdAuvPrEIhl1osMvCvIht82MijV5i6Ua5N790N0RalLVF324NrLqOdlBBFyBgJJlkbYwpJmvLxDTVqXq3T0lmPui2aeOLZ3rpGkvwH43q5Tb5nrgDsH0/nSJOxhCIxTTk++j2O3VLt1MUsXts4uF5x6Ztnf9b3WsC6Qt8zrErWrKwVUWdaE38AwVEcS0K65r4HfJMLJ/eSdh6/EcEkkpYHosAcQMLm9+lHVm03uzh1CKQJIt1GmYlwQSiqv6cVwVKIagsjVJRGkQeOBDAkTDAPTeTlROTZqXI8jxvz6yDANvns8aOqkV663J3QeDwjBAzCq4YYkHoj+bGhOreR5mScJisD7xPpMFlXdEzqBt7izX2cMlLJ4cCu7AuZ2i8HmgM95CLh6CeFwikI49ZWrsZThbUJFa1ejrxadpEjugvmfJuzbp/0RwfKWsd6OEt2UpSQFqGgeTwZwObRKNszUQLu56z/thIePXOIHUmjBzNnhzJLBMrXTDdLA74DoQYXzaVoV2BwBuYzOOiUu/stFxn4TaukfDFyAAkgJMSJNkYjTqC6+lInqU3Pfspf5+XXiX0ombHqong=
